parameters:
  - name: Environment
    default: ''
  - name: vmImage
    default: ''

jobs:
  - job: Apply
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - checkout: self
      - task: AzureCLI@1
        displayName: Get service principal credentials
        inputs:
          azureSubscription: ${{ parameters.Environment }}
          scriptLocation: inlineScript
          addSpnToEnvironment: true
          failOnStandardError: true
          inlineScript: |
            # Define environment variables
            export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
            export ARM_TENANT_ID=$(az account show --query tenantId -o tsv)
            export ARM_CLIENT_ID=$servicePrincipalId
            export ARM_CLIENT_SECRET=$servicePrincipalKey

            # Set pipeline variables for use in subsequent tasks
            echo "##vso[task.setvariable variable=arm_subscription_id]${ARM_SUBSCRIPTION_ID}"
            echo "##vso[task.setvariable variable=arm_tenant_id]${ARM_TENANT_ID}"
            echo "##vso[task.setvariable variable=arm_client_id]${ARM_CLIENT_ID}"
            echo "##vso[task.setvariable variable=arm_client_secret]${ARM_CLIENT_SECRET}" 
      - task: Bash@3
        displayName: Run Terraform Apply
        inputs:
          targetType: 'inline'
          script: |
            terraform init -backend-config=./environments/$(ENVIRONMENT)/backend.hcl
            terraform workspace new $(ENVIRONMENT)
            terraform plan -var-file=./environments/$(ENVIRONMENT)/$(ENVIRONMENT).tfvars -out=./plan/plan-$(ENVIRONMENT)
            terraform apply -auto-approve "./plan/plan-$(ENVIRONMENT)" 